// export const jobs = [
//   {
//     id: "1",
//     title: "oftware Developer",
//     company: "Tech Solutions Chennai",
//     location: "Remote",
//     workMode: "Remote",
//     description:
//       "Must have designing, coding, testing, & maintaining software applications to meet user business needs.",
//     salaryRange: "₹6 LPA - ₹10 LPA",
//     benefits: [
//       "Health Insurance",
//       "Provident Fund (PF)",
//       "Paid Leaves",
//       "Annual Bonus",
//     ],
//     responsibilities: [
//       "Develop and maintain web applications using Java and Spring Boot",
//       "Collaborate with cross-functional teams to design and implement new features",
//       "Ensure high performance, reliability, and security in applications",
//       "Debug and troubleshoot software issues",
//       "Participate in Agile development processes",
//     ],
//     requiredSkills: ["Java", "Spring Boot", "MySQL", "REST API", "Git", "Docker"],
//     education: "B.E/B.Tech in Computer Science or equivalent",
//     experience: "2-5 Years",
//     techSkills: ["Java", "Spring Boot", "MySQL", "REST API", "Git", "Docker"],
//     softSkills: ["Strong analytical thinking", "Problem-solving", "Teamwork"],
//   },
//   {
//     id: "2",
//     title: "Heavy Vehicle Mechanic",
//     company: "Tyreshop Virudhunagar",
//     location: "Onsite",
//     workMode: "On-site",
//     description:
//       "Must have inspecting, diagnosing, repairing, and maintaining heavy-duty vehicles and equipment.",
//     salaryRange: "₹3 LPA - ₹5 LPA",
//     benefits: ["Health Insurance", "Overtime Pay", "Tool Allowance"],
//     responsibilities: [
//       "Inspect and diagnose heavy vehicle issues",
//       "Perform routine maintenance and repairs",
//       "Maintain detailed service records",
//       "Ensure safety standards compliance",
//     ],
//     requiredSkills: ["Heavy Vehicle Repair", "Diagnostic Tools", "Welding", "Hydraulics"],
//     education: "ITI in Automobile or equivalent",
//     experience: "3-7 Years",
//     techSkills: ["Heavy Vehicle Repair", "Diagnostic Tools", "Welding", "Hydraulics"],
//     softSkills: ["Attention to detail", "Physical stamina", "Safety consciousness"],
//   },
//   {
//     id: "3",
//     title: "Electrical Engineer",
//     company: "PowerGrid Coimbatore",
//     location: "On Site",
//     workMode: "On-site",
//     description:
//       "Must have design, develop, and maintain electrical systems to ensure safe, efficient, and reliable operation.",
//     salaryRange: "₹5 LPA - ₹8 LPA",
//     benefits: ["Health Insurance", "PF", "Travel Allowance", "Performance Bonus"],
//     responsibilities: [
//       "Design and develop electrical systems",
//       "Conduct system testing and troubleshooting",
//       "Ensure compliance with safety regulations",
//       "Collaborate with project teams",
//     ],
//     requiredSkills: ["Circuit Design", "AutoCAD", "PLC Programming", "Power Systems"],
//     education: "B.E/B.Tech in Electrical Engineering",
//     experience: "2-4 Years",
//     techSkills: ["Circuit Design", "AutoCAD", "PLC Programming", "Power Systems"],
//     softSkills: ["Problem-solving", "Attention to detail", "Communication"],
//   },
//   {
//     id: "4",
//     title: "HR Manager",
//     company: "JK Talent Solutions",
//     location: "Onsite",
//     workMode: "Hybrid",
//     description:
//       "Must have drive employee engagement, ensure compliance, and align talent strategy with business goals.",
//     salaryRange: "₹7 LPA - ₹12 LPA",
//     benefits: [
//       "Health Insurance",
//       "Performance Bonus",
//       "Professional Development",
//       "Flexible Hours",
//     ],
//     responsibilities: [
//       "Manage recruitment and selection processes",
//       "Develop HR policies and procedures",
//       "Handle employee relations and grievances",
//       "Ensure legal compliance",
//     ],
//     requiredSkills: ["Recruitment", "HR Policies", "Employee Relations", "Performance Management"],
//     education: "MBA in HR or equivalent",
//     experience: "5-8 Years",
//     techSkills: ["HRIS Systems", "MS Excel", "Recruitment Tools"],
//     softSkills: ["Leadership", "Communication", "Conflict resolution", "Empathy"],
//   },
//   {
//     id: "5",
//     title: "Civil Engineer",
//     company: "BuildRight Constructions",
//     location: "Onsite",
//     workMode: "On-site",
//     description:
//       "Must have oversee planning, designing & managing construction projects to ensure safety, efficiency.",
//     salaryRange: "₹4 LPA - ₹7 LPA",
//     benefits: [
//       "Health Insurance",
//       "Site Allowance",
//       "Transportation",
//       "Annual Bonus",
//     ],
//     responsibilities: [
//       "Plan and design construction projects",
//       "Supervise construction activities",
//       "Ensure quality and safety standards",
//       "Coordinate with contractors and stakeholders",
//     ],
//     requiredSkills: ["Structural Design", "AutoCAD", "Project Management", "Site Supervision"],
//     education: "B.E/B.Tech in Civil Engineering",
//     experience: "3-6 Years",
//     techSkills: ["AutoCAD", "Structural Analysis", "Project Management Software"],
//     softSkills: ["Leadership", "Problem-solving", "Communication", "Time management"],
//   },
//   {
//     id: "6",
//     title: "Accountant",
//     company: "Finance Hub Erode",
//     location: "Onsite",
//     workMode: "On-site",
//     description:
//       "Must have ensure accurate financial record-keeping, compliance, and insightful reporting to support Pvt Ltd.",
//     salaryRange: "₹3.5 LPA - ₹6 LPA",
//     benefits: ["Health Insurance", "PF", "Professional Certification Support"],
//     responsibilities: [
//       "Maintain accurate financial records",
//       "Prepare financial statements and reports",
//       "Handle tax compliance and filing",
//       "Assist in budgeting and forecasting",
//     ],
//     requiredSkills: ["Accounting", "Tally", "GST", "Financial Reporting", "Tax Filing"],
//     education: "B.Com/M.Com in Accounting or CA",
//     experience: "2-5 Years",
//     techSkills: ["Tally", "Excel", "GST Software", "Banking Software"],
//     softSkills: ["Attention to detail", "Analytical thinking", "Time management", "Integrity"],
//   },
// ];
